### ISSUE TITLE
歌词不以时间开头时无法加载(￣ε(#￣) Σ

### ISSUE THREAD

**Issue by kokororin** [kirainmoe/ymplayer#3]
比如[錯覚CROSSROADS](https://kokororin.github.io/ymplayer-demo/)
去掉歌词中```[al:錯覚CROSSROADS]\n[by:菜籽酱]\n[00:00.42]\n```后正常
 _(:з」∠)_

**Comment by kirainmoe** [comment]
_(:з」∠)_ [by:] 被过滤掉了，然而忘记把 al 也过滤掉……

现在先用过滤吧……再想想有什么办法解析出来_(:з」∠)_
