### ISSUE TITLE
Element not found

### ISSUE THREAD

**Issue by ghost** [kirainmoe/ymplayer#4]
Found in your blog when switch pages, a compatiblity problem with PJAX? :joy:
![screenshot](https://cloud.githubusercontent.com/assets/16880191/12967908/f89e0f74-d0a5-11e5-8306-5757ecb50ef5.png)

**Comment by kirainmoe** [comment]
呃……也许是我把demo的代码直接贴过去了……

**Comment by kirainmoe** [comment]
_ (:з」∠) _pjax 的锅，it may be fixed.

**Comment by kirainmoe** [comment]
抱歉还有问题。日后解决。

**Comment by zxc135781** [comment]
围观
